### ISSUE TITLE
Can this work when using a multi atlas for the player sprite?

### ISSUE THREAD

**Issue by awweather** [Annoraaq/phaser-grid-movement-plugin#31]
Or does it only work with a single tilesheet?

**Comment by awweather** [comment]
I love the plugin by the way, I've been searching for something like this for a long time!
I'm assuming the api requires characterIndex to handle the animations, but I don't know how/if that works with a multi-atlas created uses TexturePacker.

**Comment by Annoraaq** [comment]
Hey @awweather,

I am happy that you like the plugin. I am thankful for any feedback because this gives me a better idea about the most common use cases.

Regarding your question. The characterIndex is the index of the character in a sprite sheet. The following image shows a sprite sheet with multiple characters. The plugin assumes each char frame to be equal in size and arranged as you see in the image. The number shown is the characterIndex.

![charIndex](https://user-images.githubusercontent.com/4518664/106497804-cd8bff00-64be-11eb-8214-15bd4845323b.png)

Do you suggest to make the plugin more flexible in that sense?

**Comment by awweather** [comment]
Correct - When using a multi atlas sprite, you can generate "keys" that can be used to play a certain animation.
Here's a snippet from my code - it would be nice if I could give the plugin which animations to play for each direction, or something like that.  

![image](https://user-images.githubusercontent.com/19537970/106517439-7d08a780-64a6-11eb-9816-1b2f35aba6e7.png)


I'll preface this with the fact that I'm using click to move.  I haven't dug into the plugin code too much, so I'm not sure how it decides which direction the player is currently facing, but I would think there could be a way to associate a direction to an animation key.

**Comment by Annoraaq** [comment]
The plugin is constructed in a way, that you don't need to pass any animations. It will animate the walking player itself. The reason for this is that the speed of the animation depends on the speed of the player on the tilemap. One tile is one "step". One "step" means moving one leg forth and back. The legs are moved in alternating order. So if last tile the right leg was movent the left one will be moved next tile and so on.

This means that the plugins needs 3 frames per direction for each character. In the example image above every character has 4 rows (one for each direction). Each row has 3 columns (left leg, standing, right leg). As long as you are within these constraints (4 directions with 3 frames each), I could enable you to explicitly set the frame numbers. That would give you the freedom to reorder your frames as you like (for example only one row).

Would that solve your problem or do you need more flexibility?

For example consider the following

**Comment by Annoraaq** [comment]
Another solution would be to let you disable the walking animation of the plugin, so that you have complete freedom with your  animations.

**Comment by awweather** [comment]
I think I see what you're saying.

Are you familiar with TexturePacker?  With a multi-atlas, you have a json file that defines the frames of a sprite, rather than using the index of a spritesheet as the frames.  For example, I have 3 frames for walking down in my walk_down animation which looks like this json below.  

` "frames": [
        {
          "filename": "walk_down/Sprite_claudius_walk_02.png",
          "rotated": false,
          "trimmed": false,
          "sourceSize": {
            "w": 32,
            "h": 60
          },
          "spriteSourceSize": {
            "x": 0,
            "y": 0,
            "w": 32,
            "h": 60
          },
          "frame": {
            "x": 1,
            "y": 1,
            "w": 32,
            "h": 60
          }
        },
        {
          "filename": "walk_down/Sprite_claudius_walk_03.png",
          "rotated": false,
          "trimmed": false,
          "sourceSize": {
            "w": 31,
            "h": 60
          },
          "spriteSourceSize": {
            "x": 0,
            "y": 0,
            "w": 31,
            "h": 60
          },
          "frame": {
            "x": 35,
            "y": 1,
            "w": 31,
            "h": 60
          }
        },
        {
          "filename": "walk_down/Sprite_claudius_walk_05.png",
          "rotated": false,
          "trimmed": false,
          "sourceSize": {
            "w": 30,
            "h": 60
          },
          "spriteSourceSize": {
            "x": 0,
            "y": 0,
            "w": 30,
            "h": 60
          },
          "frame": {
            "x": 68,
            "y": 1,
            "w": 30,
            "h": 60
          }
        },
]`

The json tells phaser where to look for the sprite.  TexturePacker will take a bunch of individual images and pack them into one png.  So my spritesheet actually looks like this.

![image](https://user-images.githubusercontent.com/19537970/106626708-facfc000-6545-11eb-9a71-2acd111ed92a.png)


So in my case, I don't believe my spritesheet meets the constraint defined by the plugin.  In my situation, I know the frames needed to walk in any direction, but I can't figure out how to let the plugin know since it requires an index for the sprite sheet.  The code snippet I showed in my last post showed how I call the animation based on the direction of the character.  The animation is just phasers way of playing those three frames in a loop until input stops.

After finding your plugin though, I am switching to click-to-move rather than arrow keys.  Apologies if I'm still missing something.  But I'm looking for a way to take my pre-defined animations (just a loop of frames), and apply them based on character direction.

**Comment by Annoraaq** [comment]
I am not familiar with TexturePacker but I will take a look at it and the phaser integration to make it more compatible with this plugin.

I see 3 possible solutions to make your sprite work with the plugin:

1. (more like a workaround) You could change the format of the png and load it as a spritesheet.

2. I add a config flag to turn off walking animations and you can deal with this outside of the plugin. However, I would still have to extend the API to let you check if the player is moving (and into which direction).

3. I extend the plugin in a way that you can somehow define the frames for the different states of the character (turned direction and which leg is lifted). But with this approach you would still have the problem, that in the image that you posted, the character has more states. Is this maybe because you have one animation for running and one for walking? I am not sure how I could solve this problem.
One Idea to make it work is to let you define more than one animation mapping. Then if you want to let your player run, you could switch the animation mapping and the players speed at the same time. But I see this last point as a related but separate issue.

I think solution 2 and 3 should both be implemented.

I will get familiar with TexturePacker and try to implement solution 3. 
I will also allow to change that animation mapping and the speed. I think that should solve your problem.

**Comment by awweather** [comment]
I'm suggesting mainly because I knowing using multi-atlas in this way is pretty common in phaser, and I haven't found another plugin that does what this does (at least one that was easily usable).

For your #3 - I am still on the train of letting the user pass you in animation keys..something like this, what do you think?
![image](https://user-images.githubusercontent.com/19537970/106650811-58bdd100-6561-11eb-8f04-dc52b62d7e49.png)

So then in your plugin somewhere, when you figure out which direction to move, rather than left foot/right foot, you just do character.anims.play("WALK_LEFT").

Then you wouldn't have to worry about how many frames are in each sprite sheet.

Is the right/left leg lifted logic for making sure that each step is a different leg?  In that case yeah..it might be a little weird for the animation to be playing if it doesn't line up exactly with 1 tile = 1 step.

**Comment by Annoraaq** [comment]
There are mainly two reasons why I did move away from using animations for the plugin:

1. The animation is time controlled. Means that the animation has a speed in frames/second. But in a tile-based movement it looks weird if the movement is not aligned with the tiles. It looks smoother if the state of the animation is exactly aligned with the position of the player. This is why I consider it so important that one step is always one tile. In a pixel based world this it not an issue.

2. Not always starting with the same foot. This is not easily manageable with animations (though I am sure there is a way but it might be quite complex). If you are doing several single steps in a row into the same direction it looks uneasy if always the same foot starts.

In fact, the plugin tightly binds the frame to the position on the tile. So for example if player is making a step: 0-50% of step -> left foot, 50-100% -> standing. That is a very simple but robust solution that solves the above problems.

But of course, this only works with 3 frames per walking direction.
I am thinking about offering both solutions to the user. Allow to pass animation keys and animation frame mappings.

**Comment by awweather** [comment]
That makes a lot of sense now that I've thought about it.  I did switch from time-based to tile based (with your plugin), so my animation technique might be a bit stale in that regard.  I'm not totally attached to this spritesheet either - so I may end up replacing it down the line.  But I do think there's some value there in offering that flexibility!

**Comment by Annoraaq** [comment]
I will work on point 2 and 3 and let you know as soon as you can try it out. Thank you for your help. At first I will implement the possibility to provide a custom frame mapping. As a next step I will enable passing animation keys. Then you can find out for yourself which animation you like better.

**Comment by Annoraaq** [comment]
Hey @awweather,

please check out this branch: https://github.com/Annoraaq/phaser-grid-movement-plugin/tree/feature/%2333-custom-anim-mapping. If you check the examples folder there, you will see 2 examples:

1. custom-walking-animation-mapping
This demonstrates how you can use the build-in animation logic of the plugin by providing a custom frame mapping.

2. custom-walking-animation
This is the most flexible solution. I made it possible to deactivate the animations of the plugin. On the other hand I added 3 observables that enable you to react to the movement. Therefore you have the complete freedom with your animations.
The example shows how to create animations using the observables.

It would be great if you could give me some feedback on this.

Cheers

**Comment by awweather** [comment]
@Annoraaq Thanks for the quick turn around! I'll give it a shot and let you know what I think.

**Comment by awweather** [comment]
@Annoraaq On the surface it looks like this should do what I need!  I can subscribe to the different movement events and play my own animation based on the direction.

Question on the example below..
What is walkingAnimationMapping?


![image](https://user-images.githubusercontent.com/19537970/107157631-22ae9180-6953-11eb-9be9-cb85c586df9a.png)

**Comment by Annoraaq** [comment]
It replaced the characterIndex. When passing a number it is the character index. Otherwise it expects an animation mapping object.

You can still use characterIndex though (to be backwards compatible). It should also be updated in the readme. Only the observables are missing in there, yet.

**Comment by Annoraaq** [comment]
But actually it is not needed in the example. I should correct that.

**Comment by awweather** [comment]
Oh that makes sense, sorry. 

I use the npm version so I'm not sure if there's an easy way to test it in my implementation before you merge it, but as far as I can tell this does everything I need.

I would just subscribe to these three observables for each of the characters I have on the screen, and then I can control their animations from there.

**Comment by Annoraaq** [comment]
In case you are using the npm version and just want to try it out, the simplest (but quite hacky) way is to navigate to your `node_modules/phaser-grid-movement-plugin/dist` directory and replace the `GridMovementPlugin.min.js` file by the one found on the branch in the `dist`  directory.

Just be aware that it might be overwritten if you run `npm install` again 

If you still run into any errors this might be due to browser caching. Just start a new instance in incognito mode to be sure.

**Comment by awweather** [comment]
@Annoraaq Wasn't sure if that would work :D I'll give that a try today and let you know how it works.

**Comment by awweather** [comment]
@Annoraaq In my testing, the subscription to movementStopped doesn't work as I'd expect.  The direction seems to always match whatever is passed back into movementStarted.  I would expect that movementStopped would get called with the "none" direction, or if it was called once the character was no longer moving. But that is not what I am seeing.

![image](https://user-images.githubusercontent.com/19537970/107284018-24e41f00-6a2b-11eb-96dc-3d5f6f72c54c.png)

**Comment by awweather** [comment]
Is movement stopped called at the end of every step?

**Comment by Annoraaq** [comment]
@awweather 

Regarding your first question: the movement stopped observable always provides the direction of the movement that was stopped. For example if the player was moving DOWN and stoppend, movementStopped will provide direction 'down'. The reason is that you might need that information (as in my example) to provide the correct stopping animation. It is never called with direction 'none'.

To come to the second question:
No it should not fire on the end of each step, but I discovered that it does, when using the `moveTo()` method of the plugin. I will fix this.
How did you start the movement? Did you use `moveTo()`? 

Independend of the bug, I think moveTo would be what you need if using a mouse based movement as you described.

Just be aware what happens if you use `moveTo()` to a current tile: If there is no path to the tile (because it is blocked) the character will not move at all. I plan to add an option that. The character would then move to a reachable tile, with aa minimum distance to the target.
If the path is NOT blocked the player will move along one (there are possible more) shortest paths to the target.

**Comment by awweather** [comment]
@Annoraaq  Thanks for the clarification.

I do indeed use MoveTo to move the player.  Everything actually works pretty smoothly using the movementStarted observable.  I can click on a tile and my animation plays correctly.  It's just when I was trying to use movementStopped, it introduced some weird behavior.

**Comment by Annoraaq** [comment]
Ok good to know. It should not be a problem to fix this. This behavior was not intended.

I will let you know as soon as I fixed it.

Thank you for testing and helping!

**Comment by Annoraaq** [comment]
@awweather I just pushed a fix to the branch. If you replace it in your node_modules again it should work.

**Comment by awweather** [comment]
@Annoraaq works great! Thanks for coming up with an easy to implement solution.

https://gyazo.com/2ec96c7345374e2111b5d80ec4064b18

**Comment by Annoraaq** [comment]
@awweather It's great to hear that! I will merge that branch, create a release and let you know about it, so you can just update it in your package.json.

Thanks again for your help. Btw: I am always curious to know about projects using the plugin. So feel free to share it with me if you like. I can also mention your project in the readme.

**Comment by Annoraaq** [comment]
@awweather Version 1.4.0 is published on npm and should contain the new implementation.

If you discover new feature requests during your project, feel free to open up new issues. It is very useful to me to know what people need the most.

**Comment by awweather** [comment]
@Annoraaq thank you! I'll go ahead and update.  My project isn't ready for sharing yet. but I'll let you know if there's anything specific I need related to the plugin.  I'm building a 2d multiplayer rpg and its awesome to have something like this to handle the tile based movement on the client side.
