### ISSUE TITLE
Moving functions return undefined

### ISSUE THREAD

**Issue by borkowsky** [Annoraaq/phaser-grid-movement-plugin#39]
Moving functions return undefined

**Comment by Annoraaq** [comment]
Hi @borkowsky, I assume you mean that the `moveLeft`, `moveRight`, etc. methods?
They always return undefined on purpose.
What do you suggest them to return instead?

**Comment by borkowsky** [comment]
> Hi @borkowsky, I assume you mean that the `moveLeft`, `moveRight`, etc. methods?
> They always return undefined on purpose.
> What do you suggest them to return instead?

Maybe return new position?

**Comment by Annoraaq** [comment]
The problem is, that they are not synchronous methods. You can see them more as a "fire and forget" command.
A good comparison would be to see them like a keypress in a game. You can press the key as often as you want and the game will notice, but it will decide whether or not a keypress is changing the player position or not.

In this plugin it is as follows: if you take a look at the "move-player" example you see that a pressed key will trigger a call to on e of the `move` methods on every update. But not each of these calls causes a position change. They only tell the game that you would like to move a player.

Therefore it is not possible to return a new position. But if you tell me what you need it for, I can maybe tell you how to achieve this differently. And if not possible, I could extend the plugin in a way that helps you and other users.

Since Version 1.4 there are some observables that you can use to react to events like `movementStarted`, `movementStopped` or `directionChanged`.

**Comment by borkowsky** [comment]
Thanks for the answers, i just need to use getPosition method.

**Comment by Annoraaq** [comment]
You're welcome. I am playing with the thought of adding an observable that fires on every position change. Depending on your use case that could prevent you from polling.
