### ISSUE TITLE
Add destroy() method

### ISSUE THREAD

**Issue by borkowsky** [Annoraaq/phaser-grid-movement-plugin#86]
Hi there. I want to suggest to add destroy() method to the plugin. It will be useful on such cases like restart scene (i do it and have large memory leaks) and etc. I need to clearup resources like characters data, created animations by plugin etc.

**Comment by Annoraaq** [comment]
Makes sense. Will be tackled soon. Thanks for your input 👍

**Comment by Annoraaq** [comment]
@borkowsky 

I checked the code and could not find any place where the plugin is creating any resources like sprites, animations, etc.
All the resources get passed from the outside to plugin. So you need to destroy() those objects from the outside as well.

It should not be in the plugin because it can't know if you still need the resources at some other place.

I think your memory leak comes from some other place. Maybe this helps: https://phaser.discourse.group/t/memory-leak-in-my-game/5839

If you find out with the chrome debugger, that it is a part of the plugin, please let me know. Then I know where to look. But I would be surprised.

**Comment by borkowsky** [comment]
Maybe add method to remove all characters or smth like that. I remove all chars now with forEach charData in plugin.

**Comment by Annoraaq** [comment]
Were you able to resolve the memory leak by looping over all chars and removing them from the plugin?

**Comment by Annoraaq** [comment]
I just ran a small experiment with the chrome memory profiler:

I repeatedly reloaded the scene with `this.scene.reload()`. On creation of the scene I created a new char sprite and added it with a random name to the plugin. The memory did not grow even with hundreds of scene reloads.

Do you call the plugins `create()` method from within the `create()` method of the scene? Because then the references to the chars are let go anyway.

Btw: I can still add the removeAllChars method if that helps you. I am just trying to understand how a memory leak can happen so I can prevent it also for other cases.

**Comment by borkowsky** [comment]
Yes, but i do some things, not only removing characters (destroy map, sprites, deattach events etc)

**Comment by borkowsky** [comment]
I think this method should be helpful :)

**Comment by Annoraaq** [comment]
The new methods: `getAllCharacters()` and `removeAllCharacters()` are merged to master and will be in the next release.
